### PR TITLE
AUTO MERGE!

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgirouxdev/testnet/31)

### CODE REVIEW

**Review by girouxchris1017 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Review by girouxchris1017 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Review by justfold101786 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/31)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[`test.js` line 5 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/31#-NAaKP14BQHvqIRbhiGW:-NAaKP14BQHvqIRbhiGX:b-ebp9uw) ([raw file](https://github.com/cgirouxdev/testnet/blob/da58db5e876d39a023814875e20bae3d88d685ef/test.js#L5)):*
> ```JavaScript
> }
> 
> console.log('HELLO!!');
> ```

NEED TO FIX THIS!

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/31)* status: all files reviewed, 1 unresolved discussion (waiting on @justfold101786)

___
*[`test.js` line 5 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/31#-NAaKP14BQHvqIRbhiGW:-NAaKWGJ-7uRODmIv6SH:b-896fix) ([raw file](https://github.com/cgirouxdev/testnet/blob/da58db5e876d39a023814875e20bae3d88d685ef/test.js#L5)):*
<details><summary><i>Previously, justfold101786 wrote…</i></summary><blockquote>

NEED TO FIX THIS!
</blockquote></details>

Done.

**Review by justfold101786 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Pull request merged**
