### PR TITLE
Newest PR

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgirouxdev/testnet/14)

### CODE REVIEW

**Review by justfold101786 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 2 of 3 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 2 of 3 files at r6, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: 0 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N7b7JfoA9tUZtBi3Uix:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N7bKT68B8qWW8CYap3G:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
123

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N808sWs9zh0KcBFb0nq:b2ngxzh)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by cgiroux86** [comment]
123

**Review by cgiroux86 — COMMENTED** [review]
123

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N8132QfCT203VcAi90p:b2ngxzh)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
123

> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, 2 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N816iRE3NL8So8EC3Ww:b2ngxzh)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
123

> Reviewed 2 of 2 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N819mVL2se8_rt7lQsO:b2ngxzh)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by cgiroux86 — COMMENTED** [review]
123

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N814Sp-DHs8VVATKMfq:b2ngxzh)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N81Dfl1AMj5soA54jTC:b45h)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
123

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N89SFv08AM4WsoZNJzi:b2ngxzh)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`test.js` line 5 at r14](http://localhost:8080/reviews/cgirouxdev/testnet/14#-N89XuOZ3tUWy2U3uVzR:-N89XuOZ3tUWy2U3uVzS:bs07t6q) ([raw file](https://github.com/cgirouxdev/testnet/blob/40e181c322743b13a2b7028811fc303a73a34469/test.js#L5)):*
> ```JavaScript
> }
> 
> console.log('HELLO!');
> ```

Hello world!

**Review by cgiroux86 — COMMENTED** [review]
123

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N89Z8mJ7E2JYrqQRHQ_:b2ngxzh)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by cgiroux86 — COMMENTED** [review]
:lgtm_strong: 
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N89abnt8C1KZma0RwHY:bte9339)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
123

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N89bFRU1kFVugv7mO5y:b2ngxzh)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
123

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N89bTQA6JdRRyLQX-4D:b2ngxzh)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
123

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N89buyhAHv4b1zAfhhM:b2ngxzh)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Review by justfold101786 — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 1 of 2 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N8DpibV9rZyY-gthDDJ:b45h)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Review by justfold101786 — APPROVED** [review]
> Reviewed 1 of 2 files at r15, 1 of 1 files at r16.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Review by justfold101786 — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N8Dr2fH3caY-KJazKaQ:b45h)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Review by cgiroux86 — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N8F_fPG4a-8mN7w92-h:b-uwkowd)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Review by cgiroux86 — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/14#-:-N8FaH4Y65Rx3gh1mJeq:b45h)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Comment by justfold101786** [comment]
+label:bug

**Comment by cgiroux86** [comment]
+bug

**Comment by cgiroux86** [comment]
-bug

**Comment by justfold101786** [comment]
+bug

**Comment by justfold101786** [comment]
+@girouxchris1017

**Comment by justfold101786** [comment]
-bug

**Comment by justfold101786** [comment]
-@girouxchris1017

**Comment by justfold101786** [comment]
(completed)

**Comment by justfold101786** [comment]
+bug

**Comment by justfold101786** [comment]
+@girouxchris1017

**Comment by justfold101786** [comment]
-bug

**Comment by justfold101786** [comment]
+@cgiroux86

**Comment by justfold101786** [comment]
-@cgiroux86

**Pull request merged**
