### PR TITLE
HELLO AUTO MERGE!

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgirouxdev/testnet/25)

### CODE REVIEW

**Review by justfold101786 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/25)* status: 0 of 2 LGTMs obtained

___
*[`-- commits` line 2 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/25#-NA_qJPG7_4Lgw6vhn5H):*
Why caps?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/25)* status: 0 of 2 LGTMs obtained

___
*[`-- commits` line 2 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/25#-NA_qJPG7_4Lgw6vhn5H):*
<details><summary><i>Previously, justfold101786 wrote…</i></summary><blockquote>

Why caps?
</blockquote></details>

Done.

**Review by justfold101786 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/25)* status: 0 of 2 LGTMs obtained

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/25)* status: 0 of 2 LGTMs obtained

___
*[`another.js` line 1 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/25#-NA_q_uH7WBMO8CJA5hw:-NA_q_uH7WBMO8CJA5hx:b-ysu26v) ([raw file](https://github.com/cgirouxdev/testnet/blob/59ddc7923c941dff32dc317fb521acf8517b8246/another.js#L1)):*
> ```JavaScript
> console.log('ANOTHER FILE!!');
> ```

Why did we get rid of this?

**Review by justfold101786 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/25)* status: 0 of 2 LGTMs obtained

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/25)* status: 0 of 2 LGTMs obtained

___
*[`another.js` line 1 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/25#-NA_q_uH7WBMO8CJA5hw:-NA_qm5B25U836kcodMX:b-896fix) ([raw file](https://github.com/cgirouxdev/testnet/blob/59ddc7923c941dff32dc317fb521acf8517b8246/another.js#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Why did we get rid of this?
</blockquote></details>

Done.

**Review by girouxchris1017 — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/25#-:-NA_qxZ3DmbB8Eiay0RA:b-uwkowd)* status: 1 of 2 LGTMs obtained

**Review by justfold101786 — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/25#-:-NA_r0uA3tYh2GS5Co04:b-uwkowd)* status: :shipit: complete! 2 of 2 LGTMs obtained

**Pull request merged**
