### PR TITLE
Update test.js

### PR DESCRIPTION
**Pull request by cgiroux86**
Co-Authored-By: girouxchris1017 <79605020+girouxchris1017@users.noreply.github.com>

- - -
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgirouxdev/testnet/45)

### CODE REVIEW

**Review by justfold101786 — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @girouxchris1017)

**Review by girouxchris1017 — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Review by justfold101786 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Review by girouxchris1017 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Pull request merged**
