### PR TITLE
AUTO MERRGING IS FUN!

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgirouxdev/testnet/26)

### CODE REVIEW

**Review by justfold101786 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/26)* status: 0 of 2 LGTMs obtained

**Review by girouxchris1017 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/26)* status: 0 of 2 LGTMs obtained

___
*[`-- commits` line 2 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/26#-NA_ryeRDO8Iy8bCM4SP):*
BLOCKED!
___
*[`another.js` line 1 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/26#-NA_s2UM4JVxwjoiJOgV:-NA_s2UM4JVxwjoiJOgW:b-p0icpl) ([raw file](https://github.com/cgirouxdev/testnet/blob/6758dee8dce7f2b04e58acbb32b426f6fd127f4a/another.js#L1)):*
> ```JavaScript
> console.log('ANOTHER FILE!!');
> ```

BLOCKING!

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/26)* status: 0 of 2 LGTMs obtained

___
*[`-- commits` line 2 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/26#-NA_ryeRDO8Iy8bCM4SP):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

BLOCKED!
</blockquote></details>

Done.
___
*[`another.js` line 1 at r1](http://localhost:8080/reviews/cgirouxdev/testnet/26#-NA_s2UM4JVxwjoiJOgV:-NA_sBc43DgvRhd7SiqN:b-896fix) ([raw file](https://github.com/cgirouxdev/testnet/blob/6758dee8dce7f2b04e58acbb32b426f6fd127f4a/another.js#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

BLOCKING!
</blockquote></details>

Done.

**Review by girouxchris1017 — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/26#-:-NA_t1wt11hxL3yByDMn:b-uwkowd)* status: 1 of 2 LGTMs obtained

**Review by cgiroux86 — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](http://localhost:8080/reviews/cgirouxdev/testnet/26#-:-NA_tpm27sZ0zs36aAM3:b-uwkowd)* status: :shipit: complete! 2 of 2 LGTMs obtained

**Pull request merged**
